# -*- coding: utf-8 -*-
"""Project 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D9XJgMSUJ5fxNOaqssS4aurxCXePRg2g
"""

import numpy as np 
import pandas as pd 
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Attrition data.csv')
df.head()

df.shape

df.describe()

df.isnull().sum()

attrition_count = pd.DataFrame(df['Attrition'].value_counts())
attrition_count

plt.pie(attrition_count['Attrition'] , labels = ['No' , 'Yes'] , explode = (0.2,0))

df.drop(['EmployeeID' , 'Age'] , axis = 1)

attrition_dummies = pd.get_dummies(df['Attrition'])
attrition_dummies.head()

df = pd.concat([df, attrition_dummies] , axis = 1)
df.head()

df = df.drop(['Attrition' , 'No'] , axis = 1)
df.head()

sns.barplot(x = 'Gender' , y = 'Yes', data = df)

sns.barplot(x = 'Department', y = 'Yes', data = df)

sns.barplot(x = 'BusinessTravel', y = 'Yes', data = df)

plt.figure(figsize = (10,6))
sns.heatmap(df.corr())

df = df.drop(['Age' , 'JobLevel'], axis = 1)

from sklearn.preprocessing import LabelEncoder
for column in df.columns:
    if df[column].dtype==np.number:
        continue
    else:
        df[column]=LabelEncoder().fit_transform(df[column])

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)

x  = df.drop(['Yes'], axis = 1)
y = df['Yes']

x_train, x_test , y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 0)

x_train.head()